import { BUSINESS_TYPES } from "@/platform/businessTypes";
import type { ScenarioInput } from "../registry";

export const freightForwarder: ScenarioInput = {
  id: "freight-forwarder",
  businessType: "freight_forwarder",
  label: "Freight Forwarder",
  icon: "box",
  cardDescription: "Manage receiving, warehousing, manifests, shipments, tracking and customers from one system.",
  exampleWorkflow: ["Receive in Miami", "Consolidate", "Manifest", "Nassau", "Out island", "Delivered"],
  organizationName: "Island Gateway Logistics",
  tagline: "Your forwarding operation, connected.",
  user: { name: "Renee Thompson", role: "Operations Manager" },
  enabledModules: BUSINESS_TYPES.freight_forwarder.modules,
  steps: [
    {
      id: "dashboard",
      nav: "overview",
      title: "Operations dashboard",
      description: "Every shipment, receipt, manifest and delivery feeds one live picture. Exceptions surface on their own — nobody has to go looking.",
      task: "Open an alert to send it to the right team.",
      screen: {
        kind: "dashboard",
        data: {
          heading: "Good morning, Renee — Tuesday operations",
          metrics: [
            { label: "Active shipments", value: "42", sub: "+6 since yesterday", icon: "box" },
            { label: "Receiving today", value: "18", sub: "Miami warehouse", icon: "inbox" },
            { label: "In transit", value: "27", sub: "Ocean 19 · Air 8", icon: "ship" },
            { label: "Deliveries pending", value: "11", sub: "Nassau 7 · Family Islands 4", icon: "truck", tone: "warn" },
          ],
          aiSummary: "4 shipments require attention today.",
          alerts: [
            { id: "a1", tone: "warn", area: "Receiving · Miami", title: "SH-10479 waiting on receiving confirmation", detail: "Docked 3 h ago. Carrier weight 41 kg, scale 36 kg.", action: "Confirm receipt" },
            { id: "a2", tone: "bad", area: "Manifest · TRP-1042", title: "Nassau → Eleuthera manifest nearing cutoff", detail: "Cutoff 2:00 PM. 3 shipments still unassigned.", action: "Open manifest" },
            { id: "a3", tone: "warn", area: "Delivery · Freeport", title: "DLV-338 delivery delayed", detail: "Driver reports road works on Queen's Highway. 2 stops pushed.", action: "Reschedule" },
            { id: "a4", tone: "info", area: "Customer · WhatsApp", title: "Mrs. Rolle awaiting an update on SH-10431", detail: "Asked 2 h ago: “Has my fridge reached Exuma?”", action: "Send update" },
          ],
          board: {
            title: "Today's departures",
            columns: ["Trip", "Route", "Mode", "Departs", "Shipments", "Status"],
            rows: [
              { cells: ["TRP-1041", "Miami → Nassau", "Air", "11:40 AM", "14"], status: "Loading", tone: "info" },
              { cells: ["TRP-1042", "Nassau → Eleuthera", "Mailboat", "4:00 PM", "12"], status: "Cutoff 2 PM", tone: "warn" },
              { cells: ["TRP-1043", "Nassau → Freeport", "Ocean", "6:00 PM", "9"], status: "Scheduled", tone: "neutral" },
            ],
          },
        },
      },
    },
    {
      id: "receiving",
      nav: "warehouse",
      title: "Receiving",
      description: "Cargo arrives at the Miami warehouse. Receiving checks each piece in, captures weight and starts the customer's tracking — one scan, everywhere updated.",
      task: "Click “Receive Shipment”.",
      screen: {
        kind: "receive",
        data: {
          ref: "SH-10482",
          route: "Miami → Nassau",
          customer: "John Smith",
          facts: [
            { label: "Final destination", value: "Governor's Harbour, Eleuthera" },
            { label: "Service", value: "Ocean consolidation" },
            { label: "Container", value: "ISG-2207" },
            { label: "Declared value", value: "$1,940.00" },
          ],
          packages: [
            { id: "PKG-55101", description: "Washing machine (boxed)", weightKg: 22 },
            { id: "PKG-55102", description: "Patio chairs ×2", weightKg: 18 },
            { id: "PKG-55103", description: "Kitchen supplies", weightKg: 14 },
            { id: "PKG-55104", description: "Hurricane shutters kit", weightKg: 12 },
            { id: "PKG-55105", description: "School supplies", weightKg: 10 },
            { id: "PKG-55106", description: "Clothing", weightKg: 8 },
          ],
          receiveLabel: "Receive Shipment",
          afterReceive: ["Bin assigned: MIA-C14", "John notified on WhatsApp", "Customs entry draft created", "Queued for container ISG-2207"],
        },
      },
    },
    {
      id: "manifest",
      nav: "manifest",
      title: "Manifest",
      description: "Cleared shipments for Eleuthera are ready for the 4:00 PM mailboat. Shipping OS knows what's ready, so the manifest builds itself instead of being typed up from paper.",
      task: "Click “Build Manifest”, then close it before cutoff.",
      screen: {
        kind: "manifest",
        data: {
          trip: { ref: "TRP-1042", route: "Nassau → Eleuthera", vessel: "MV Eleuthera Express", departs: "Today 4:00 PM", cutoff: "2:00 PM" },
          columns: [
            { key: "ref", label: "Shipment" },
            { key: "consignee", label: "Consignee" },
            { key: "pieces", label: "Pcs", numeric: true },
            { key: "kg", label: "Weight (kg)", numeric: true },
            { key: "dest", label: "Destination" },
          ],
          weightKey: "kg",
          lines: [
            { ref: "SH-10482", consignee: "John Smith", pieces: "6", kg: "84", dest: "Governor's Harbour" },
            { ref: "SH-10437", consignee: "Rock Sound Pharmacy", pieces: "4", kg: "62", dest: "Rock Sound" },
            { ref: "SH-10441", consignee: "Pink Sands Villas", pieces: "3", kg: "48", dest: "Harbour Island" },
            { ref: "SH-10445", consignee: "Marvin Seymour", pieces: "2", kg: "31", dest: "Gregory Town" },
            { ref: "SH-10450", consignee: "Eleuthera Hardware", pieces: "5", kg: "95", dest: "Governor's Harbour" },
            { ref: "SH-10452", consignee: "Kayla Cartwright", pieces: "1", kg: "22", dest: "Tarpum Bay" },
            { ref: "SH-10458", consignee: "Hatchet Bay Marina", pieces: "3", kg: "57", dest: "Hatchet Bay" },
            { ref: "SH-10461", consignee: "Dr. P. Gibson", pieces: "2", kg: "40", dest: "Rock Sound" },
            { ref: "SH-10466", consignee: "Cove Eleuthera Resort", pieces: "4", kg: "73", dest: "Gregory Town" },
            { ref: "SH-10470", consignee: "Island Bakery", pieces: "3", kg: "66", dest: "Governor's Harbour" },
            { ref: "SH-10473", consignee: "Tarpum Bay Clinic", pieces: "2", kg: "54", dest: "Tarpum Bay" },
            { ref: "SH-10476", consignee: "Sandra Johnson", pieces: "3", kg: "52", dest: "Harbour Island" },
          ],
          insight: "12 shipments are ready for this trip.",
          buildLabel: "Build Manifest",
          finalize: { label: "Close manifest", done: "Manifest closed — 12 shipments, 684 kg locked to TRP-1042. Purser copy sent to MV Eleuthera Express." },
        },
      },
    },
    {
      id: "tracking",
      nav: "tracking",
      title: "Tracking",
      description: "Every scan, sailing and delivery writes to one timeline — the same one your team, your drivers and your customer see.",
      task: "Record the next scans and follow SH-10482 to the door.",
      screen: {
        kind: "timeline",
        data: {
          ref: "SH-10482",
          customer: "John Smith",
          route: ["Miami", "Nassau", "Eleuthera"],
          startAt: 3,
          events: [
            { label: "Received", place: "Miami warehouse", time: "Mon 9:14 AM", detail: "6 pieces · 84 kg · bin MIA-C14", at: 0 },
            { label: "Warehouse processed", place: "Miami warehouse", time: "Mon 1:40 PM", detail: "Consolidated into container ISG-2207", at: 0 },
            { label: "Arrived Nassau", place: "Arawak Cay Port", time: "Wed 6:05 AM", detail: "Customs released 11:20 AM", at: 1 },
            { label: "In transit", place: "MV Eleuthera Express", time: "Wed 4:10 PM", detail: "TRP-1042 · Nassau → Governor's Harbour", at: 1.5 },
            { label: "Arrived Eleuthera", place: "Governor's Harbour dock", time: "Thu 7:30 AM", detail: "Unloaded, out for delivery 9:00 AM", at: 2 },
            { label: "Delivered", place: "Governor's Harbour", time: "Thu 11:52 AM", detail: "Signed by J. Smith · photo captured", at: 2 },
          ],
        },
      },
    },
    {
      id: "portal",
      nav: "portal",
      title: "Customer portal",
      description: "This is John's view. Status, documents and arrival time are always current, so customers stop calling and WhatsApp-ing your office for updates.",
      task: "Turn on WhatsApp updates from the customer's side.",
      screen: {
        kind: "portal",
        data: {
          brand: "Island Gateway",
          customer: "John Smith",
          ref: "SH-10482",
          status: "On the mailboat to Eleuthera",
          eta: "Thursday, by 12:00 PM",
          progress: [
            { label: "Received in Miami", time: "Mon 9:14 AM", done: true },
            { label: "Arrived in Nassau", time: "Wed 6:05 AM", done: true },
            { label: "On the way to Eleuthera", time: "Wed 4:10 PM", done: true },
            { label: "Out for delivery", time: "Thu morning", done: false },
            { label: "Delivered", time: "", done: false },
          ],
          documents: [
            { name: "Commercial invoice", kind: "PDF" },
            { name: "Customs entry", kind: "PDF" },
            { name: "Bill of lading ISG-2207", kind: "PDF" },
          ],
          whatsapp: "Hi John 👋 SH-10482 left Nassau on MV Eleuthera Express at 4:10 PM. We expect it in Governor's Harbour Thursday morning. Reply 1 for delivery, 2 for dock pickup.",
        },
      },
    },
    {
      id: "ai",
      nav: "ai",
      title: "AI operations",
      description: "Ask in plain language. The assistant reads the same shipments, manifests and conversations you just saw and turns them into a work queue — it suggests, your team decides.",
      task: "Ask “What needs my attention today?”",
      screen: {
        kind: "ai",
        data: {
          prompt: "What needs my attention today?",
          suggestions: ["Which shipments are delayed?", "What's left before the 2 PM cutoff?"],
          answer: [
            { type: "text", text: "Five things need a person today. In order of urgency:" },
            {
              type: "items",
              items: [
                { tone: "bad", title: "Manifest issue — TRP-1042 (cutoff 2:00 PM)", detail: "3 shipments for Eleuthera have no customs invoice: SH-10484, SH-10487, SH-10490." },
                { tone: "bad", title: "Delayed — DLV-338, Freeport", detail: "Road works on Queen's Highway. 2 deliveries move to tomorrow unless rerouted." },
                { tone: "warn", title: "Receiving exception — SH-10479", detail: "Carrier says 41 kg, scale says 36 kg. Not confirmed for 3 hours." },
                { tone: "warn", title: "Delivery problem — 2 Nassau drops without a window", detail: "SH-10455 and SH-10468 are out today with no confirmed time." },
                { tone: "info", title: "Customer follow-ups — 5 WhatsApp questions over 2 h old", detail: "Mrs. Rolle (SH-10431), Bain Hardware, Coral Cay Resort and 2 others." },
              ],
            },
          ],
          draft: { label: "Create work queue", title: "Draft work queue — 5 tasks", lines: ["Customs: request invoices for SH-10484, 10487, 10490 (due 1:30 PM)", "Dispatch: reroute DLV-338 via Settlement Road or move to Wed", "Warehouse: re-weigh SH-10479 and confirm", "Dispatch: confirm windows for SH-10455, SH-10468", "Support: reply to 5 WhatsApp threads (drafts attached)"] },
          closing: "Shipping OS turned your operation's activity into an actionable work queue.",
        },
      },
    },
  ],
  completion: {
    headline: "Your forwarding operation, connected.",
    points: ["Receiving in Miami updated stock, tracking and the customer at once", "The manifest built itself from cleared cargo", "Customers serve themselves instead of calling", "AI turned the day's noise into five clear tasks"],
  },
};
